# vi: set ft=ruby

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'
  #config.vm.box = 'chef/centos-7.0'
  #config.vm.box = 'chef/centos-6.5'
  #config.vm.box = 'chef/fedora-20'

  config.vm.network :forwarded_port, :host => 8000, :guest => 8000

  config.vm.provision :shell, inline: <<-eof
    set -o errexit
  eof

  config.vm.provider :virtualbox do |v|
    v.customize ['modifyvm', :id, '--cpus', ENV['VM_CPUS'] || '4']
    v.customize ['modifyvm', :id, '--memory', ENV['VM_MEMORY'] || 1024]
    v.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    v.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
    v.customize ['setextradata', :id, 'VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root', '1']
  end

  config.ssh.forward_agent = true
end
